application:
  name: "actm"
  version: "0.1.0"
  description: "A CLI tool to export activity listings from the Active Mississauga website, supporting filters and multiple output formats."
log_config_file: "config/logging.yml"
web_driver: "/usr/bin/chromedriver" # path to chromedriver

input:
  folder: "data/input"
  files:

output:
  folder: "data/output"

home_url: "https://activemississauga.ca/"

filters:
  activities:
    save_format: "csv"
    when:
      session_checkboxes:
        - "2025"
      days_of_week:
        - "Monday"
        - "Tuesday"
        - "Wednesday"
        - "Thursday"
        - "Friday"
        - "Saturday"
        - "Sunday"
      status: "Future"
      skip_single_date: true
    who:
      age_from: 10
      age_to: 10
      skip_all_ages: true
#    where:
#      locations:
#        - "Community Centre" # replace with actual location names to filter
#        - "Community Library" # replace with actual location names to filter
    name:
      not_contains:
        - "Extended Hours"
        - "Private Lessons"
        - "Preschool"
        - "Lane Swim"
        - "Fun Swim"
        - "Parent & Tot Swim"
        - "Swim For Life Parent & Tot"
        - "Drop In"
        - "Drop-In"
